<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Guna.UI2.WinForms" Version="2.0.4.7" />
    <PackageReference Include="Microsoft.Graph.Beta" Version="0.47.0-preview" />
    <PackageReference Include="MySql.Data" Version="9.5.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="infraestructure\adapters\output\" />
  </ItemGroup>

</Project>